# application-local.yml (로컬 개발 환경)
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false

  sql:
    init:
      mode: always
      encoding: utf-8

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
    org.springframework.security: debug
    com.onemorethink.domadosever.global: debug