# application-prod.yml (운영 환경)
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect  # 추가
    hibernate:
      ddl-auto: create-drop
    show-sql: true  # 변경
    properties:
      hibernate:
        format_sql: true  # 변경
        default_batch_fetch_size: 100
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      encoding: UTF-8  # 추가 (한글 데이터 때문에)

logging:
  level:
    root: INFO  # 추가
    org.hibernate.SQL: DEBUG  # 변경
    org.hibernate.type.descriptor.sql: TRACE  # 변경
    org.springframework.security: DEBUG  # 변경
    com.onemorethink.domadosever: DEBUG  # 변경
  file:
    name: ./logs/application.log

# APNs 설정 추가
apns:
  bundle-id: ${APNS_BUNDLE_ID}
  certificate:
    path: ${APNS_CERT_PATH}
    password: ${APNS_CERT_PASSWORD}
    # 개발용 APNs 서버 사용 (배포 시에는 production으로 변경 필요)
  production: false 